#pragma once

#define VERSION_FMT(x) #x
#define VERSION_STR(x) VERSION_FMT(x)

#define ZDTALK_RECORDER_VERSION_MAJOR  1
#define ZDTALK_RECORDER_VERSION_MINOR  0
#define ZDTALK_RECORDER_VERSION_PATCH  3

#define ZDTALK_RECORDER_VERSION ZDTALK_RECORDER_VERSION_MAJOR.ZDTALK_RECORDER_VERSION_MINOR.ZDTALK_RECORDER_VERSION_PATCH
#define ZDTALK_RECORDER_VERSION_STR VERSION_STR(ZDTALK_RECORDER_VERSION)
